slam_toolbox:
  ros__parameters:
    # Parametry ramek (Kluczowe!)
    odom_frame: odom
    map_frame: map
    base_frame: base_link
    scan_topic: scan
    use_sim_time: true
    use_imu_data: false # Włączamy wsparcie dla IMU
    imu_topic: /imu    # Nazwa tematu z Twojego mostka

    # Tryb pracy
    mode: mapping 

    # Parametry sensora
    max_laser_range: 10.0
    minimum_time_interval: 0.1
    transform_timeout: 0.2
    tf_buffer_duration: 30.
    stack_size_to_use: 40000000 

    # Ustawienia publikacji (Zwolnione, by nie przeciążać Gazebo)
    map_update_interval: 2.0
    resolution: 0.05
    transform_publish_period: 0.05 # 20Hz - wystarczy dla stabilności

    # Parametry dopasowania skanów (Scan Matching)
    # Zmniejszone progi, aby SLAM "wybaczał" drgania fizyki robota
    minimum_travel_distance: 0.05
    minimum_travel_heading: 0.05
    
    # Parametry korelacji (Zwiększona precyzja)
    link_match_minimum_response_fine: 0.1
    link_scan_maximum_distance: 1.5
    loop_search_maximum_distance: 3.0
    do_loop_closing: true

    # Ustawienia korelacji przestrzennej
    correlation_search_space_dimension: 0.5
    correlation_search_space_resolution: 0.01
    correlation_search_space_smear_deviation: 0.1

    # Optymalizacja
    max_get_map_retry_count: 5
    enable_interactive_mode: true